version: '3.9'

services:

  image:
    container_name: poc-pix-hyperf.image
    image: poc-pix-hyperf
    command: list
    build: .

  app:
    container_name: poc-pix-hyperf.app
    image: poc-pix-hyperf
    working_dir: /app
    entrypoint: ["php", "bin/hyperf.php", "start"]
    volumes:
      - ./:/app
    ports:
      - '9501:9501'
    networks:
      - bubble

networks:
    bubble:
      external: true
