version: '3.9'

services:

  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf/hyperf:8.0-alpine-v3.14-swoole
    working_dir: /app
    entrypoint: ["php", "bin/hyperf.php", "start"]
    volumes:
      - ./:/app
    ports:
      - 9501:9501
    networks:
      - bubble

networks:
    bubble:
      external: true
